// AUTO-GENERATED by tools/extract_font_data.py from SLES_523.84.
// Font texture-bank descriptors (SPRT_DAT fntdat[6]) recovered from the PS2
// ELF.  Included once by g2d_main.c.  Do not edit by hand.

#ifndef _GRAPH2D_FNTDAT_DATA_H
#define _GRAPH2D_FNTDAT_DATA_H


SPRT_DAT fntdat[6] = {
    { .tex0 = 0x2007e105e6420460ull, .u = 0, .v = 0, .w = 512, .h = 70, .x = 0, .y = 0, .pri = 0, .alpha = 128, .flip = 0, .bln = 0 },
    { .tex0 = 0x2007e14626420860ull, .u = 0, .v = 0, .w = 512, .h = 256, .x = 0, .y = 0, .pri = 0, .alpha = 128, .flip = 0, .bln = 0 },
    { .tex0 = 0x2007e18626421060ull, .u = 0, .v = 0, .w = 512, .h = 256, .x = 0, .y = 0, .pri = 0, .alpha = 128, .flip = 0, .bln = 0 },
    { .tex0 = 0x2007e90626c20000ull, .u = 0, .v = 0, .w = 512, .h = 256, .x = 0, .y = 0, .pri = 0, .alpha = 128, .flip = 0, .bln = 0 },
    { .tex0 = 0x2007e94626c20800ull, .u = 0, .v = 0, .w = 512, .h = 256, .x = 0, .y = 0, .pri = 0, .alpha = 128, .flip = 0, .bln = 0 },
    { .tex0 = 0x2007e98626c21000ull, .u = 0, .v = 0, .w = 512, .h = 256, .x = 0, .y = 0, .pri = 0, .alpha = 128, .flip = 0, .bln = 0 }
};


#endif /* _GRAPH2D_FNTDAT_DATA_H */
