// FILE: /home/zero_rom/zero2np/src/graphics/motion/acs_dat.c
//
// Accessory data: the collision primitives, weighted-MIME hair springs, rope
// shapes and cloth definitions that mdldat.c's manmdl_dat[] and accessory.c's
// rope_tbl[] point into.  The whole object is data -- acs_dat.o's 0xd4 bytes
// of .text are only the fixed_array<> range-check helpers the compiler emitted
// for headers this file included, and it exports no functions at all.
//
// Generated by tools/reverse/extract_acs_dat.py from .data at
// 0x2d1ae0..0x2d4370 in the Feb 6 2004 prototype (SLES_523.84).  That script
// re-encodes the text below and diffs it against the ROM image before writing,
// so all 10384 bytes across the 266 objects are known to match exactly.
//
// One deliberate deviation.  GCC 2.96-ee converted decimal float literals by
// rounding *toward zero* rather than to nearest, so 28 of the constants here
// sit one ulp below what a modern compiler produces from the same decimal --
// the ROM holds 0.97999996 where "0.98f" gives 0.98000002.  The decimals below
// are the literals the original source had, which is what a source
// reconstruction wants; the host build's bit patterns therefore differ from
// the ROM's by that single ulp on those constants.

#include "acs_dat.h"

/* --------------------------------------------------------------------------
 *  Collision primitives
 *
 *  Referenced by the COLLISION_DAT tables further down, which pair each shape
 *  with the bone it rides on.  COLLISION_DAT::type picks the test: 0 sphere,
 *  1 tube, anything else plane.  All of these are in model-local units.
 * ------------------------------------------------------------------------ */

SPHERE sphere_R35 = { { 0.0f, 0.0f, 0.0f, 1.0f }, 38.0f };
SPHERE sphere_R50 = { { 0.0f, -50.0f, -5.0f, 1.0f }, 50.0f };
SPHERE sphere_R70 = { { 0.0f, -300.0f, 0.0f, 1.0f }, 70.0f };
SPHERE sphere_R100 = { { 0.0f, 0.0f, 0.0f, 1.0f }, 100.0f };
SPHERE sphere_R150 = { { 0.0f, 0.0f, 0.0f, 1.0f }, 150.0f };
SPHERE sphere_R200 = { { 0.0f, 0.0f, 0.0f, 1.0f }, 200.0f };
TUBE tube_R150_H200 = { { -100.0f, 0.0f, 0.0f, 1.0f }, { 100.0f, 0.0f, 0.0f, 1.0f }, 180.0f, 0 };
TUBE tube_R90_H200 = { { -100.0f, 0.0f, 0.0f, 1.0f }, { 100.0f, 0.0f, 0.0f, 1.0f }, 70.0f, 0 };
SPHERE sphere_mio = { { 0.0f, -50.0f, -5.0f, 1.0f }, 50.0f };
SPHERE sphere_hako = { { 0.0f, -50.0f, 0.0f, 1.0f }, 50.0f };
TUBE tube_momol_mio = { { -15.0f, 0.0f, 5.0f, 1.0f }, { 200.0f, 0.0f, 5.0f, 1.0f }, 45.0f, 0 };
TUBE tube_momor_mio = { { -15.0f, 0.0f, -5.0f, 1.0f }, { 200.0f, 0.0f, -5.0f, 1.0f }, 45.0f, 0 };
SPHERE sphere_face = { { 40.0f, 0.0f, 0.0f, 1.0f }, 60.0f };
SPHERE sphere_rakka = { { 50.0f, 0.0f, 0.0f, 1.0f }, 38.0f };
SPHERE sphere_kubiore = { { 50.0f, 0.0f, 0.0f, 1.0f }, 38.0f };
TUBE tube_waningyou_head = { { 37.0f, 10.0f, 0.0f, 1.0f }, { 27.0f, 10.0f, 0.0f, 1.0f }, 40.0f, 0 };
TUBE tube_waningyou = { { 30.0f, -5.0f, 24.0f, 1.0f }, { 30.0f, -5.0f, -24.0f, 1.0f }, 55.0f, 0 };
TUBE tube_up_leg_l = { { 0.0f, 10.0f, 10.0f, 1.0f }, { 140.0f, 0.0f, 10.0f, 1.0f }, 40.0f, 0 };
TUBE tube_low_leg_l = { { 0.0f, 0.0f, 10.0f, 1.0f }, { 200.0f, 0.0f, 10.0f, 1.0f }, 40.0f, 0 };
TUBE tube_up_leg_r = { { 0.0f, 10.0f, -10.0f, 1.0f }, { 140.0f, 0.0f, -10.0f, 1.0f }, 40.0f, 0 };
TUBE tube_low_leg_r = { { 0.0f, 0.0f, -10.0f, 1.0f }, { 200.0f, 0.0f, -10.0f, 1.0f }, 40.0f, 0 };
TUBE tube_momol = { { -5.0f, 0.0f, 0.0f, 1.0f }, { 150.0f, 0.0f, 5.0f, 1.0f }, 35.0f, 0 };
TUBE tube_momor = { { -5.0f, 0.0f, 0.0f, 1.0f }, { 150.0f, 0.0f, -5.0f, 1.0f }, 35.0f, 0 };
TUBE tube_momo_sae = { { -50.0f, 0.0f, 0.0f, 1.0f }, { 200.0f, 0.0f, 5.0f, 1.0f }, 45.0f, 0 };
CPLANE plane_floor = { { 0.0f, 1.0f, 0.0f, 0.0f }, -5.0f };
CPLANE plane_ituki = { { 0.7071068f, 0.0f, -0.7071068f, 0.0f }, 2400.0f };

/* --------------------------------------------------------------------------
 *  Weighted MIME (hair) springs
 *
 *  Every table below is one spring plus the NULL sentinel the reader stops on.
 *  The name is matched against the model's MIME channel names, bone_id is the
 *  bone the spring hangs off, and pos/gravity are its rest offset and pull.
 * ------------------------------------------------------------------------ */

WMIM mimacs_hair_dat0 = { (u_char *)"hair", 0.02f, 0.02f, 0.9f,
      { 0.0f, 3.0f, 0.0f, 1.0f },
      { 0.0f, -0.4f, 0.0f, 0.0f } };
WMIM_DAT ch000_wmim_tbl[2] = {
    { &mimacs_hair_dat0, 2 },
    { NULL, 0 },
};
WMIM mimacs_hair_dat1 = { (u_char *)"hair", 0.02f, 0.02f, 0.9f,
      { 0.0f, 3.0f, 0.0f, 1.0f },
      { 0.0f, -0.4f, 0.0f, 0.0f } };
WMIM_DAT ch001_wmim_tbl[2] = {
    { &mimacs_hair_dat1, 2 },
    { NULL, 0 },
};
WMIM mimacs_hair_dat3 = { (u_char *)"hair", 0.02f, 0.02f, 0.9f,
      { 0.0f, -2.0f, 0.0f, 1.0f },
      { 0.0f, -0.4f, 0.0f, 0.0f } };
WMIM_DAT ch003_wmim_tbl[2] = {
    { &mimacs_hair_dat3, 2 },
    { NULL, 0 },
};
WMIM mimacs_hair_dat17 = { (u_char *)"hair", 0.02f, 0.02f, 0.9f,
      { 0.0f, 0.0f, 0.0f, 1.0f },
      { 0.0f, -0.4f, 0.0f, 0.0f } };
WMIM_DAT ch017_wmim_tbl[2] = {
    { &mimacs_hair_dat17, 2 },
    { NULL, 0 },
};
WMIM mimacs_hair_dat30 = { (u_char *)"hair", 0.01f, 0.02f, 0.9f,
      { 0.0f, 0.0f, 0.0f, 1.0f },
      { 0.0f, -0.4f, 0.0f, 0.0f } };
WMIM_DAT ch030_wmim_tbl[2] = {
    { &mimacs_hair_dat30, 2 },
    { NULL, 0 },
};
WMIM mimacs_hair_dat39 = { (u_char *)"hair", 0.02f, 0.02f, 0.9f,
      { 0.0f, 0.0f, 0.0f, 1.0f },
      { 0.0f, -0.4f, 0.0f, 0.0f } };
WMIM_DAT ch039_wmim_tbl[2] = {
    { &mimacs_hair_dat39, 2 },
    { NULL, 0 },
};

/* --------------------------------------------------------------------------
 *  Ropes
 *
 *  A vtx[] list is the chain's Y offsets running down from the anchor,
 *  terminated by a negative entry -- the table itself decides how many
 *  particles a rope has.  acsInitRopeSub scales them by 25 into model units.
 * ------------------------------------------------------------------------ */

float rope_vtx0[4] = { 0.0f, 11.2f, 25.0f, -1.0f };
ROPE_DAT rope_dat0 = { rope_vtx0, 2.5f, 0.98f, 0.01f, 1 };
float sudare_vtx0[4] = { 0.0f, 8.6f, 18.5f, -1.0f };
ROPE_DAT sudare_dat0 = { sudare_vtx0, 2.5f, 0.98f, 0.01f, 1 };
float genkan_vtx000[4] = { 0.0f, 7.5f, 11.0f, -1.0f };
ROPE_DAT fr_genkan000 = { genkan_vtx000, 2.5f, 0.98f, 0.01f, 1 };
float genkan_vtx001[4] = { 0.0f, 13.3f, 17.0f, -1.0f };
ROPE_DAT fr_genkan001 = { genkan_vtx001, 2.5f, 0.98f, 0.01f, 1 };
float irori_vtx000[4] = { 0.0f, 29.3f, 34.4f, -1.0f };
ROPE_DAT fr_irori_dentou000 = { irori_vtx000, 2.5f, 0.98f, 0.01f, 1 };
float irori_vtx001[4] = { 0.0f, 17.0f, 22.3f, -1.0f };
ROPE_DAT fr_irori_dentou001 = { irori_vtx001, 2.5f, 0.98f, 0.01f, 1 };
float oozasiki_vtx000[4] = { 0.0f, 6.8f, 10.8f, -1.0f };
ROPE_DAT fr_oozasiki_dentou000 = { oozasiki_vtx000, 2.5f, 0.98f, 0.01f, 1 };
float butuma_vtx000[4] = { 0.0f, 11.2f, 14.6f, -1.0f };
ROPE_DAT fr_butuma_dentou000 = { butuma_vtx000, 2.5f, 0.98f, 0.01f, 1 };
float okunoma_vtx000[4] = { 0.0f, 11.2f, 14.6f, -1.0f };
ROPE_DAT fr_okunoma_dentou000 = { okunoma_vtx000, 2.5f, 0.98f, 0.01f, 1 };
float okunoma_vtx001[4] = { 0.0f, 10.5f, 13.9f, -1.0f };
ROPE_DAT fr_okunoma_dentou001 = { okunoma_vtx001, 2.5f, 0.98f, 0.01f, 1 };
float okunoma_vtx002[4] = { 0.0f, 11.2f, 15.0f, -1.0f };
ROPE_DAT fr_okunoma_sudare000 = { okunoma_vtx002, 2.5f, 0.98f, 0.01f, 1 };
ROPE_DAT fr_okunoma_sudare001 = { okunoma_vtx002, 2.5f, 0.98f, 0.01f, 1 };
ROPE_DAT fr_okunoma_sudare002 = { okunoma_vtx002, 2.5f, 0.98f, 0.01f, 1 };
float kyakuma_vtx000[4] = { 0.0f, 6.2f, 19.2f, -1.0f };
ROPE_DAT fr_kyakuma_dentou000 = { kyakuma_vtx000, 2.5f, 0.98f, 0.01f, 1 };
float shouzi_vtx000[4] = { 0.0f, 9.4f, 12.8f, -1.0f };
ROPE_DAT fr_shouzi000 = { shouzi_vtx000, 2.5f, 0.98f, 0.01f, 1 };
float rry01_genkan_vtx[3][5] = {
    { 0.0f, 10.86f, 18.02f, 29.52f, -1.0f },
    { 0.0f, 12.9f, 21.43f, 32.53f, -1.0f },
    { 0.0f, 12.6f, 20.94f, 31.81f, -1.0f },
};
ROPE_DAT fr_rry01_genkan_turi000 = { rry01_genkan_vtx[0], 2.5f, 0.98f, 0.01f, 1 };
ROPE_DAT fr_rry01_genkan_turi001 = { rry01_genkan_vtx[1], 2.5f, 0.98f, 0.01f, 1 };
ROPE_DAT fr_rry01_genkan_turi002 = { rry01_genkan_vtx[2], 2.5f, 0.98f, 0.01f, 1 };
float toumyou_vtx000[4] = { 0.0f, 4.0f, 10.0f, -1.0f };
ROPE_DAT fr_rry00_toumyou000 = { toumyou_vtx000, 2.5f, 0.98f, 0.01f, 1 };
ROPE_DAT fr_rry00_toumyou001 = { toumyou_vtx000, 2.5f, 0.98f, 0.01f, 1 };
float rkh00_vtx000[4] = { 0.0f, 8.64f, 17.28f, -1.0f };
float rkh00_vtx001[4] = { 0.0f, 9.0f, 18.0f, -1.0f };

/* NOTE: ROM data as-is.  Unlike every other list here this one has no negative
 * terminator, so the seeding loop in acsInitRopeSub runs off the end of it.
 * On the PS2 it walked into the ROPE_DATs that follow and stopped at the -1.0f
 * inside rtb08_vtx000, 31 particles later -- past the end of the 20-slot
 * particle array.  Rope types 24 and 25 (fr_rkh00_rope003/004) are the two
 * that use it.  Do not "fix" the data; the host layout differs anyway, so if
 * those two types ever load, guard the loop in accessory.c instead. */
float rkh00_vtx002[4] = { 0.0f, 21.0f, 39.0f, 53.0f };
ROPE_DAT fr_rkh00_rope001 = { rkh00_vtx000, 2.5f, 0.98f, 0.01f, 1 };
ROPE_DAT fr_rkh00_rope002 = { rkh00_vtx001, 2.5f, 0.98f, 0.01f, 1 };
ROPE_DAT fr_rkh00_rope003 = { rkh00_vtx002, 2.5f, 0.98f, 0.01f, 1 };
ROPE_DAT fr_rkh00_rope004 = { rkh00_vtx002, 2.5f, 0.98f, 0.01f, 1 };
float rtb08_vtx000[4] = { 0.0f, 9.4f, 12.8f, -1.0f };
ROPE_DAT fr_rtb08_dentou000 = { rtb08_vtx000, 2.5f, 0.98f, 0.01f, 1 };
float ry04_vtx000[4] = { 0.0f, 13.6f, 21.2f, -1.0f };

/* NOTE: ROM data as-is -- both ry04 lanterns point at rtb08_vtx000, not at the
 * ry04_vtx000 declared just above, which nothing references. */
ROPE_DAT fr_ry04_tourou000 = { rtb08_vtx000, 2.5f, 0.98f, 0.01f, 1 };
ROPE_DAT fr_ry04_tourou001 = { rtb08_vtx000, 2.5f, 0.98f, 0.01f, 1 };
sceVu0FVECTOR ry02_vtx000[2] = {
    { 0.0f, 13.6f, 21.2f, -1.0f },
    { 0.0f, 4.6f, 12.0f, -1.0f },
};
ROPE_DAT fr_ry02_tourou000 = { ry02_vtx000[0], 2.5f, 0.98f, 0.01f, 1 };
ROPE_DAT fr_ry02_tourou001 = { ry02_vtx000[1], 2.5f, 0.98f, 0.01f, 1 };
ROPE_DAT fr_ry02_tourou002 = { ry02_vtx000[0], 2.5f, 0.98f, 0.01f, 1 };
ROPE_DAT *rope_tbl[32] = {
    /*  0 */ &rope_dat0,
    /*  1 */ &sudare_dat0,
    /*  2 */ &fr_genkan000,
    /*  3 */ &fr_genkan001,
    /*  4 */ &fr_irori_dentou000,
    /*  5 */ &fr_irori_dentou001,
    /*  6 */ &fr_oozasiki_dentou000,
    /*  7 */ &fr_butuma_dentou000,
    /*  8 */ &fr_okunoma_dentou000,
    /*  9 */ &fr_okunoma_dentou001,
    /* 10 */ &fr_okunoma_sudare000,
    /* 11 */ &fr_okunoma_sudare001,
    /* 12 */ &fr_okunoma_sudare002,
    /* 13 */ &fr_kyakuma_dentou000,
    /* 14 */ NULL,
    /* 15 */ NULL,
    /* 16 */ &fr_shouzi000,
    /* 17 */ &fr_rry01_genkan_turi000,
    /* 18 */ &fr_rry01_genkan_turi001,
    /* 19 */ &fr_rry01_genkan_turi002,
    /* 20 */ &fr_rry00_toumyou000,
    /* 21 */ &fr_rry00_toumyou001,
    /* 22 */ &fr_rkh00_rope001,
    /* 23 */ &fr_rkh00_rope002,
    /* 24 */ &fr_rkh00_rope003,
    /* 25 */ &fr_rkh00_rope004,
    /* 26 */ &fr_rtb08_dentou000,
    /* 27 */ &fr_ry04_tourou000,
    /* 28 */ &fr_ry04_tourou001,
    /* 29 */ &fr_ry02_tourou000,
    /* 30 */ &fr_ry02_tourou001,
    /* 31 */ &fr_ry02_tourou002,
};

/* --------------------------------------------------------------------------
 *  Cloth definitions
 *
 *  w x h is the particle grid.  type decides how acsGetClothBufSize counts
 *  particles and springs: 0 is a plain grid, 1/2/6 double it (both faces get
 *  particles), 4/5 keep the grid but only run springs down the columns, and
 *  anything else adds the cross springs back.  type also selects which edge
 *  acsSetClothVtx pins -- 0 and 4/5 pin b_point rows at the far end.
 * ------------------------------------------------------------------------ */

CLOTH cloth_furisode3 = { 0.9f, 0.91f, 0.0f,  5,  5, 6 };
CLOTH furisode_mio = { 1.4f, 0.9f, 0.0f,  5,  5, 6 };
CLOTH cloth_skirt = { 0.94f, 0.89f, 0.0f, 20,  9, 4 };
CLOTH cloth_skirt_mio = { 0.5f, 0.93f, 0.0f, 20,  8, 4 };
CLOTH cloth_skirt_mayu = { 0.78f, 0.92f, 0.0f, 20, 12, 4 };
CLOTH cloth_skirt_miya = { 0.78f, 0.92f, 0.0f, 20,  9, 4 };
CLOTH cloth_skirt_hako = { 0.98f, 0.98f, 0.0f, 16, 13, 4 };
CLOTH cloth_skirt_manto_hako = { 0.2f, 0.9f, 0.0f, 17, 13, 0 };
CLOTH cloth_manto_hako = { 0.51f, 0.947f, 0.0f, 11, 13, 0 };
CLOTH cloth_manto_kusa1 = { 0.51f, 0.947f, 0.0f,  4,  6, 0 };
CLOTH cloth_manto_kusa2 = { 0.51f, 0.947f, 0.0f,  5,  6, 0 };
CLOTH cloth_skirt_kusa1 = { 0.78f, 0.92f, 0.0f,  3,  4, 5 };
CLOTH cloth_skirt_kusa2 = { 0.78f, 0.92f, 0.0f,  3,  6, 5 };
CLOTH cloth_manto_rakka1 = { 0.8f, 0.947f, 0.0f,  5,  5, 0 };
CLOTH cloth_manto_rakka2 = { 0.8f, 0.947f, 0.0f,  4,  7, 0 };
CLOTH cloth_skirt_rakka1 = { 0.78f, 0.92f, 0.0f, 14,  5, 5 };
CLOTH cloth_skirt_kubiore = { 0.78f, 0.92f, 0.0f, 13,  7, 5 };
CLOTH cloth_manto_waninngyou = { 0.9f, 0.947f, 0.0f,  7,  8, 0 };
CLOTH cloth_skirt_rakka2 = { 0.78f, 0.92f, 0.0f,  8,  5, 5 };
CLOTH cloth_skirt_kusakoro2 = { 0.78f, 0.92f, 0.0f,  8,  5, 5 };
CLOTH cloth_manto_noren = { 0.9f, 0.974f, 0.0f,  7,  7, 0 };
CLOTH cloth_irori_noren = { 0.9f, 0.974f, 0.0f,  4,  7, 0 };
CLOTH cloth_nuno_noren = { 0.9f, 0.974f, 0.0f,  7,  7, 0 };
CLOTH cloth_nuno_nuno = { 0.9f, 0.974f, 0.0f,  7,  7, 0 };
CLOTH cloth_genkan_noren = { 0.9f, 0.974f, 0.0f,  9, 10, 0 };
CLOTH cloth_genkan_noren2 = { 0.9f, 0.974f, 0.0f,  4, 13, 0 };
CLOTH cloth_meian_noren = { 0.9f, 0.974f, 0.0f,  4, 13, 0 };
CLOTH cloth_okunoma_sudare = { 0.9f, 0.974f, 0.0f,  7,  2, 0 };
CLOTH cloth_meian_curtain = { 0.9f, 0.974f, 0.0f, 14,  5, 0 };
CLOTH cloth_skirt_suisi = { 0.0f, 0.92f, 0.0f, 24, 20, 5 };
CLOTH cloth_skirt_tama = { 0.03f, 0.1f, 0.0f, 16,  6, 5 };
CLOTH cloth_skirt_yami2 = { 0.78f, 0.92f, 0.0f,  8,  5, 5 };
CLOTH cloth_skirt_sae = { 0.78f, 0.92f, 0.0f,  4, 12, 5 };
CLOTH cloth_skirt_imi1 = { 0.78f, 0.92f, 0.0f,  4,  6, 5 };

/* --------------------------------------------------------------------------
 *  Per-model cloth and collision tables
 *
 *  Indexed by model number through manmdl_dat[] in mdldat.c.  Both kinds of
 *  table are NULL-terminated.  CLOTH_DAT::sgd_id is the sub-file inside the
 *  model pak that carries the cloth mesh, bone_id/bone_id2 are the bones it
 *  hangs from (0xff meaning "none"), and b_point is how many rows per column
 *  acsSetClothVtx pins back to the model instead of simulating.
 *
 *  rist_vtx is not input data: acsMoveCloth and acsSetClothVtx *write* the
 *  wrist/edge vertices back into it each frame, which is why all 61 of these
 *  arrays ship as the origin with w = 1.
 *
 *  ch000, ch001, ch017, ch030, ch055 and m999 define tables here that
 *  manmdl_dat[] never points at -- the prototype's entries for those models
 *  pass NULL.  They are kept because the ROM keeps them.
 * ------------------------------------------------------------------------ */

CLOTH_DAT ch000_cloth[2] = {
    { &cloth_skirt_mio,        NULL,                3, 255,  5, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch000_collision[4] = {
    { &tube_momol_mio,       1, 12 },
    { &tube_momor_mio,       1, 23 },
    { &sphere_mio,           0,  3 },
    { NULL,                  0,  0 },
};
CLOTH_DAT ch001_cloth[2] = {
    { &cloth_skirt_mayu,       NULL,                3, 255,  3, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch001_collision[4] = {
    { &tube_momol_mio,       1, 12 },
    { &tube_momor_mio,       1, 23 },
    { &sphere_mio,           0,  3 },
    { NULL,                  0,  0 },
};
CLOTH_DAT ch003_cloth[3] = {
    { &cloth_manto_kusa2,      NULL,                8, 255, 14, 0, 1 },
    { &cloth_manto_kusa2,      NULL,                5, 255, 15, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch004_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch004_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch004_cloth[3] = {
    { &cloth_furisode3,        ch004_rist_vtx0,    13,  17,  4, 0, 1 },
    { &cloth_furisode3,        ch004_rist_vtx1,     5,   9,  5, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch006_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch006_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch006_cloth[3] = {
    { &cloth_furisode3,        ch006_rist_vtx0,     7,  11,  5, 1, 1 },
    { &cloth_furisode3,        ch006_rist_vtx1,    17,  21,  7, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch006_collision[2] = {
    { &plane_ituki,          2,  0 },
    { NULL,                  0,  0 },
};
CLOTH_DAT ch011_cloth[3] = {
    { &cloth_skirt_yami2,      NULL,               17, 255,  8, 0, 1 },
    { &cloth_skirt_yami2,      NULL,                9, 255,  9, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch013_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch013_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch013_cloth[4] = {
    { &cloth_furisode3,        ch013_rist_vtx0,     5,   9, 12, 0, 1 },
    { &cloth_furisode3,        ch013_rist_vtx1,    13,  17, 11, 0, 1 },
    { &cloth_skirt_sae,        NULL,               19, 255,  9, 1, 3 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch013_collision[2] = {
    { &tube_momo_sae,        1, 10 },
    { NULL,                  0,  0 },
};
CLOTH_DAT ch014_cloth[2] = {
    { &cloth_skirt_tama,       NULL,                1, 255,  1, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT ch017_cloth[2] = {
    { &cloth_skirt,            NULL,                3, 255,  2, 1, 3 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch017_collision[4] = {
    { &tube_momol,           1, 10 },
    { &tube_momor,           1, 18 },
    { &sphere_R50,           0,  3 },
    { NULL,                  0,  0 },
};
CLOTH_DAT ch018_cloth[6] = {
    { &cloth_manto_kusa1,      NULL,               17, 255, 16, 0, 1 },
    { &cloth_manto_kusa2,      NULL,                9, 255, 18, 0, 1 },
    { &cloth_manto_kusa2,      NULL,                5, 255, 19, 0, 1 },
    { &cloth_skirt_kusa1,      NULL,                9, 255, 10, 0, 1 },
    { &cloth_skirt_kusa2,      NULL,                4, 255, 13, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch019_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch019_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch019_cloth[3] = {
    { &cloth_furisode3,        ch019_rist_vtx0,     6,  10, 11, 1, 1 },
    { &cloth_furisode3,        ch019_rist_vtx1,    15,  19,  8, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch019_collision[2] = {
    { &plane_floor,          2,  0 },
    { NULL,                  0,  0 },
};
sceVu0FVECTOR ch020_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch020_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch020_cloth[8] = {
    { &cloth_manto_rakka1,     NULL,                3, 255,  1, 1, 1 },
    { &cloth_manto_rakka2,     NULL,               23, 255,  4, 1, 1 },
    { &cloth_skirt_rakka1,     NULL,                2, 255,  7, 1, 1 },
    { &cloth_skirt_rakka2,     NULL,               10, 255,  5, 1, 1 },
    { &cloth_skirt_rakka2,     NULL,               20, 255,  6, 1, 1 },
    { &cloth_furisode3,        ch020_rist_vtx0,     7,  11,  2, 1, 1 },
    { &cloth_furisode3,        ch020_rist_vtx1,    17,  21,  3, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch020_collision[3] = {
    { &sphere_rakka,         0,  2 },
    { &plane_floor,          2,  0 },
    { NULL,                  0,  0 },
};
sceVu0FVECTOR ch021_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch021_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch021_cloth[4] = {
    { &cloth_manto_waninngyou, NULL,                2, 255, 12, 1, 1 },
    { &cloth_furisode3,        ch021_rist_vtx0,    15,  19,  9, 1, 1 },
    { &cloth_furisode3,        ch021_rist_vtx1,     6,  10, 11, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch021_collision[4] = {
    { &tube_waningyou_head,  1,  2 },
    { &tube_waningyou,       1,  1 },
    { &plane_floor,          2,  0 },
    { NULL,                  0,  0 },
};
sceVu0FVECTOR ch022_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch022_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch022_cloth[4] = {
    { &cloth_manto_waninngyou, NULL,                2, 255, 12, 1, 1 },
    { &cloth_furisode3,        ch022_rist_vtx0,    15,  19,  9, 1, 1 },
    { &cloth_furisode3,        ch022_rist_vtx1,     6,  10, 11, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch022_collision[4] = {
    { &tube_waningyou_head,  1,  2 },
    { &tube_waningyou,       1,  1 },
    { &plane_floor,          2,  0 },
    { NULL,                  0,  0 },
};
sceVu0FVECTOR ch024_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch024_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch024_cloth[5] = {
    { &cloth_manto_hako,       NULL,                2, 255,  3, 1, 1 },
    { &cloth_manto_hako,       NULL,                2, 255,  4, 1, 1 },
    { &cloth_furisode3,        ch024_rist_vtx0,     5,   9,  5, 1, 1 },
    { &cloth_furisode3,        ch024_rist_vtx1,    13,  17,  6, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch024_collision[3] = {
    { &sphere_face,          0,  2 },
    { &plane_floor,          2,  0 },
    { NULL,                  0,  0 },
};
sceVu0FVECTOR ch025_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch025_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch025_cloth[4] = {
    { &cloth_furisode3,        ch025_rist_vtx1,     6,  10,  6, 0, 1 },
    { &cloth_furisode3,        ch025_rist_vtx0,    14,  18,  7, 0, 1 },
    { &cloth_skirt_kubiore,    NULL,                3, 255,  8, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch025_collision[2] = {
    { &sphere_kubiore,       0,  3 },
    { NULL,                  0,  0 },
};
sceVu0FVECTOR ch026_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch026_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch026_cloth[3] = {
    { &cloth_furisode3,        ch026_rist_vtx0,    13,  17,  7, 0, 1 },
    { &cloth_furisode3,        ch026_rist_vtx1,     5,   9,  8, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch027_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch027_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch027_cloth[3] = {
    { &cloth_furisode3,        ch027_rist_vtx1,    13,  17,  9, 1, 1 },
    { &cloth_furisode3,        ch027_rist_vtx0,     5,   9, 10, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch027_collision[2] = {
    { &plane_floor,          2,  0 },
    { NULL,                  0,  0 },
};
sceVu0FVECTOR ch028_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch028_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch028_cloth[3] = {
    { &cloth_furisode3,        ch028_rist_vtx1,    13,  17,  6, 1, 1 },
    { &cloth_furisode3,        ch028_rist_vtx0,     5,   9,  7, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch028_collision[2] = {
    { &plane_floor,          2,  0 },
    { NULL,                  0,  0 },
};
sceVu0FVECTOR ch029_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch029_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch029_cloth[3] = {
    { &cloth_furisode3,        ch029_rist_vtx1,    13,  17,  3, 1, 1 },
    { &cloth_furisode3,        ch029_rist_vtx0,     5,   9,  4, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch029_collision[2] = {
    { &plane_floor,          2,  0 },
    { NULL,                  0,  0 },
};
CLOTH_DAT ch030_cloth[2] = {
    { &cloth_skirt_suisi,      NULL,                3, 255,  5, 1, 2 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch030_collision[6] = {
    { &tube_momol,           1, 10 },
    { &tube_momol,           1,  6 },
    { &tube_momor,           1, 18 },
    { &tube_momor,           1, 14 },
    { &sphere_R50,           0,  3 },
    { NULL,                  0,  0 },
};
sceVu0FVECTOR ch031_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch031_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch031_cloth[3] = {
    { &cloth_furisode3,        ch031_rist_vtx1,    13,  17,  4, 1, 1 },
    { &cloth_furisode3,        ch031_rist_vtx0,     5,   9,  5, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch031_collision[2] = {
    { &plane_floor,          2,  0 },
    { NULL,                  0,  0 },
};
CLOTH_DAT ch032_cloth[2] = {
    { &cloth_skirt_imi1,       NULL,                5, 255,  4, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch033_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch033_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch033_cloth[3] = {
    { &cloth_furisode3,        ch033_rist_vtx1,     7,   8,  1, 1, 1 },
    { &cloth_furisode3,        ch033_rist_vtx0,     4,   5,  2, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch033_collision[2] = {
    { &plane_floor,          2,  0 },
    { NULL,                  0,  0 },
};
sceVu0FVECTOR ch038_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch038_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch038_cloth[3] = {
    { &cloth_furisode3,        ch038_rist_vtx1,    12,  16,  4, 0, 1 },
    { &cloth_furisode3,        ch038_rist_vtx0,     5,   9,  5, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT ch039_cloth[3] = {
    { &cloth_skirt_kusakoro2,  NULL,               11, 255,  5, 0, 1 },
    { &cloth_skirt_kusakoro2,  NULL,                6, 255,  6, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch041_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch041_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch041_cloth[3] = {
    { &cloth_furisode3,        ch041_rist_vtx1,    13,  17, 23, 0, 1 },
    { &cloth_furisode3,        ch041_rist_vtx0,     5,   9, 25, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch043_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch043_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch043_cloth[3] = {
    { &cloth_furisode3,        ch043_rist_vtx1,    13,  17,  5, 0, 1 },
    { &cloth_furisode3,        ch043_rist_vtx0,     5,   9,  4, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch044_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch044_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch044_cloth[3] = {
    { &cloth_furisode3,        ch044_rist_vtx0,     7,  11,  8, 0, 1 },
    { &cloth_furisode3,        ch044_rist_vtx1,    17,  21,  7, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch047_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch047_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch047_cloth[3] = {
    { &cloth_furisode3,        ch047_rist_vtx1,    12,  16,  2, 0, 1 },
    { &cloth_furisode3,        ch047_rist_vtx0,     5,   9,  3, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch048_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch048_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch048_cloth[3] = {
    { &cloth_furisode3,        ch048_rist_vtx1,    12,  16,  2, 0, 1 },
    { &cloth_furisode3,        ch048_rist_vtx0,     5,   9,  3, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT ch049_cloth[3] = {
    { &cloth_skirt_kusakoro2,  NULL,               11, 255,  6, 0, 1 },
    { &cloth_skirt_kusakoro2,  NULL,                6, 255,  7, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT ch053_cloth[2] = {
    { &cloth_skirt_imi1,       NULL,                5, 255,  4, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT ch055_cloth[2] = {
    { &cloth_skirt,            NULL,                3, 255,  3, 1, 3 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT ch055_collision[4] = {
    { &tube_momol,           1, 10 },
    { &tube_momor,           1, 18 },
    { &sphere_R50,           0,  3 },
    { NULL,                  0,  0 },
};
sceVu0FVECTOR ch058_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch058_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch058_cloth[3] = {
    { &cloth_furisode3,        ch058_rist_vtx0,     5,   9, 11, 0, 1 },
    { &cloth_furisode3,        ch058_rist_vtx1,    13,  17, 10, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch064_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch064_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch064_cloth[3] = {
    { &furisode_mio,           ch064_rist_vtx0,    18,  22,  7, 0, 1 },
    { &furisode_mio,           ch064_rist_vtx1,     7,  11,  8, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch065_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch065_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch065_cloth[3] = {
    { &furisode_mio,           ch065_rist_vtx0,    18,  22, 13, 0, 1 },
    { &furisode_mio,           ch065_rist_vtx1,     7,  11, 14, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch066_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch066_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch066_cloth[3] = {
    { &furisode_mio,           ch066_rist_vtx0,    18,  22,  7, 0, 1 },
    { &furisode_mio,           ch066_rist_vtx1,     7,  11,  8, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch067_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch067_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch067_cloth[3] = {
    { &furisode_mio,           ch067_rist_vtx0,    18,  22, 13, 0, 1 },
    { &furisode_mio,           ch067_rist_vtx1,     7,  11, 14, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch068_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch068_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch068_cloth[3] = {
    { &furisode_mio,           ch068_rist_vtx0,    18,  22,  7, 0, 1 },
    { &furisode_mio,           ch068_rist_vtx1,     7,  11,  8, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch069_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch069_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch069_cloth[3] = {
    { &furisode_mio,           ch069_rist_vtx0,    18,  22, 13, 0, 1 },
    { &furisode_mio,           ch069_rist_vtx1,     7,  11, 14, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch070_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch070_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch070_cloth[3] = {
    { &furisode_mio,           ch070_rist_vtx0,    18,  22,  7, 0, 1 },
    { &furisode_mio,           ch070_rist_vtx1,     7,  11,  8, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR ch071_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
sceVu0FVECTOR ch071_rist_vtx1[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT ch071_cloth[3] = {
    { &furisode_mio,           ch071_rist_vtx0,    18,  22, 13, 0, 1 },
    { &furisode_mio,           ch071_rist_vtx1,     7,  11, 14, 0, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
sceVu0FVECTOR m999_rist_vtx0[4] = {
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
    { 0.0f, 0.0f, 0.0f, 1.0f },
};
CLOTH_DAT m999_cloth[3] = {
    { &cloth_furisode3,        m999_rist_vtx0,     13,  17,  3, 0, 1 },
    { &cloth_skirt,            NULL,                3, 255,  4, 1, 3 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
COLLISION_DAT m999_collision[4] = {
    { &tube_momol,           1, 10 },
    { &tube_momor,           1, 18 },
    { &sphere_R50,           0,  3 },
    { NULL,                  0,  0 },
};

/* --------------------------------------------------------------------------
 *  Furniture cloth tables
 *
 *  Reached through furn_mdl_dat[] rather than manmdl_dat[]; these are the
 *  noren, sudare and curtains hung in individual rooms.
 * ------------------------------------------------------------------------ */

CLOTH_DAT f000_cloth[2] = {
    { &cloth_manto_noren,      NULL,                0, 255,  0, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_irori000[2] = {
    { &cloth_irori_noren,      NULL,                0, 255,  0, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_irori001[2] = {
    { &cloth_irori_noren,      NULL,                0, 255,  0, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_nuno000[2] = {
    { &cloth_nuno_noren,       NULL,                0, 255,  0, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_nuno001[2] = {
    { &cloth_nuno_nuno,        NULL,                0, 255,  0, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_nuno002[2] = {
    { &cloth_nuno_nuno,        NULL,                0, 255,  0, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_genkan000[2] = {
    { &cloth_genkan_noren,     NULL,                0, 255,  0, 1, 5 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_genkan001[2] = {
    { &cloth_genkan_noren2,    NULL,                0, 255,  0, 1, 7 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_genkan002[2] = {
    { &cloth_genkan_noren2,    NULL,                0, 255,  0, 1, 7 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_genkan003[2] = {
    { &cloth_genkan_noren2,    NULL,                0, 255,  0, 1, 7 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_genkan004[2] = {
    { &cloth_genkan_noren2,    NULL,                0, 255,  0, 1, 7 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_meian000[2] = {
    { &cloth_meian_noren,      NULL,                0, 255,  0, 1, 7 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_meian001[2] = {
    { &cloth_meian_noren,      NULL,                0, 255,  0, 1, 7 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_meian002[2] = {
    { &cloth_meian_noren,      NULL,                0, 255,  0, 1, 7 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_meian003[2] = {
    { &cloth_meian_noren,      NULL,                0, 255,  0, 1, 7 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_okunoma000[2] = {
    { &cloth_okunoma_sudare,   NULL,                0, 255,  0, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_meian004[2] = {
    { &cloth_meian_curtain,    NULL,                0, 255,  0, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
CLOTH_DAT fc_meian005[2] = {
    { &cloth_meian_curtain,    NULL,                0, 255,  0, 1, 1 },
    { NULL,                    NULL,                0,   0,  0, 0, 0 },
};
