// FILE: /home/zero_rom/zero2np/src/graphics/motion/mdldat.c
//
// Animation-code streams and model/animation lookup tables reconstructed from
// the original initialized data image.  PS2 pointers are represented by native
// C symbol references for the 64-bit port.
//
// Reconstructed from the Feb 6 2004 prototype (SLES_523.84).

#include "mdldat.h"
#include "acs_dat.h"
#include "morph_dat.h"

#include "mdldat_data.inc"
/*
 * These three tables were copied from .data at 0x320388, 0x320ad8 and
 * 0x320b68.  Pointer words in the PS2 image are expressed as their native C
 * symbols here: retaining the literal 32-bit addresses would truncate on the
 * x64 port and would also bypass ASLR.
 */
#define MAN_ENTRY(h, n, c, w, p, l, wd, cd, col) \
    { 1.0f, h, n, c, w, p, l, wd, cd, col }

MANMDL_DAT manmdl_dat[78] = {
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch000_wmim_tbl, NULL, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch001_wmim_tbl, NULL, NULL),
    MAN_ENTRY(1,  1, 1,  1, 1, 1, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 18, 3, 6, ch003_wmim_tbl, ch003_cloth, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch004_cloth, NULL),
    MAN_ENTRY(1,  1, 1,  1, 1, 1, NULL, NULL, NULL),
    MAN_ENTRY(2, 13, 1, 23, 3, 8, NULL, ch006_cloth, ch006_collision),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(1,  1, 1,  1, 1, 1, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch011_cloth, NULL),
    MAN_ENTRY(1,  1, 1,  1, 1, 1, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch013_cloth, ch013_collision),
    MAN_ENTRY(1,  1, 1,  1, 1, 1, NULL, ch014_cloth, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, ch017_wmim_tbl, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch018_cloth, NULL),
    MAN_ENTRY(2, 12, 1, 21, 3, 7, NULL, ch019_cloth, ch019_collision),
    MAN_ENTRY(2, 13, 1, 23, 3, 7, NULL, ch020_cloth, ch020_collision),
    MAN_ENTRY(2, 12, 1, 21, 3, 7, NULL, ch021_cloth, ch021_collision),
    MAN_ENTRY(2, 12, 1, 21, 3, 7, NULL, ch022_cloth, ch022_collision),
    MAN_ENTRY(1,  1, 1,  1, 1, 1, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch024_cloth, ch024_collision),
    MAN_ENTRY(3, 12, 1, 20, 4, 6, NULL, ch025_cloth, ch025_collision),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch026_cloth, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch027_cloth, ch027_collision),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch028_cloth, ch028_collision),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch029_cloth, ch029_collision),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, ch030_wmim_tbl, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch031_cloth, ch031_collision),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch032_cloth, NULL),
    MAN_ENTRY(2,  2, 1,  3, 3, 6, NULL, ch033_cloth, ch033_collision),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 18, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 18, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 18, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 18, 3, 6, NULL, ch038_cloth, NULL),
    MAN_ENTRY(2,  8, 1, 13, 3, 7, ch039_wmim_tbl, ch039_cloth, NULL),
    MAN_ENTRY(1,  1, 1,  1, 1, 1, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch041_cloth, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch043_cloth, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch044_cloth, NULL),
    MAN_ENTRY(3,  3, 3,  3, 3, 3, NULL, NULL, NULL),
    MAN_ENTRY(2,  2, 1,  1, 1, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch047_cloth, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch048_cloth, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch049_cloth, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch053_cloth, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2,  2, 2,  2, 2, 2, NULL, NULL, NULL),
    MAN_ENTRY(2,  2, 2,  2, 2, 2, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 19, 3, 6, NULL, ch058_cloth, NULL),
    MAN_ENTRY(2, 11, 1, 18, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 18, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 11, 1, 18, 3, 6, NULL, NULL, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch000_wmim_tbl, NULL, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch001_wmim_tbl, NULL, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch000_wmim_tbl, ch064_cloth, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch001_wmim_tbl, ch065_cloth, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch000_wmim_tbl, ch066_cloth, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch001_wmim_tbl, ch067_cloth, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch000_wmim_tbl, ch068_cloth, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch001_wmim_tbl, ch069_cloth, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch000_wmim_tbl, ch070_cloth, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch001_wmim_tbl, ch071_cloth, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch000_wmim_tbl, NULL, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch001_wmim_tbl, NULL, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch000_wmim_tbl, NULL, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch001_wmim_tbl, NULL, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch000_wmim_tbl, NULL, NULL),
    MAN_ENTRY(2, 14, 1, 25, 3, 5, ch001_wmim_tbl, NULL, NULL)
};

#undef MAN_ENTRY

FURNMDL_DAT furn_mdl_dat[18] = {
    { f000_cloth, NULL },
    { fc_irori000, NULL },
    { fc_nuno000, NULL },
    { fc_nuno001, NULL },
    { fc_nuno002, NULL },
    { fc_irori001, NULL },
    { fc_meian000, NULL },
    { fc_meian001, NULL },
    { fc_genkan001, NULL },
    { fc_genkan002, NULL },
    { fc_genkan003, NULL },
    { fc_genkan004, NULL },
    { fc_meian002, NULL },
    { fc_meian003, NULL },
    { fc_genkan000, NULL },
    { fc_meian005, NULL },
    { fc_meian004, NULL },
    { fc_okunoma000, NULL }
};

#define ANM_ENTRY(a, m, limit, neck) { a, m, limit, neck }
#define ANM_STD(a, m, neck) ANM_ENTRY(a, m, 1.04719746f, neck)

ANI_TBL anm_tbl[171] = {
    ANM_STD(ch000anm_tbl, NULL, NULL),
    ANM_STD(ch000anm_tbl, NULL, NULL),
    ANM_STD(ch000anm_tbl, NULL, NULL),
    ANM_STD(ch000anm_tbl, NULL, NULL),
    ANM_STD(ch001anm_tbl, NULL, NULL),
    ANM_STD(ch000anm_tbl, NULL, NULL),
    ANM_STD(ch003anm_tbl, NULL, ch003_neck_spd_tbl),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(ch005anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(ch010anm_tbl, NULL, ch010_neck_spd_tbl),
    ANM_STD(ch011anm_tbl, NULL, ch011_neck_spd_tbl),
    ANM_STD(ch012anm_tbl, NULL, NULL),
    ANM_STD(ch013anm_tbl, NULL, ch013_neck_spd_tbl),
    ANM_STD(ch014anm_tbl, NULL, NULL),
    ANM_STD(ch015anm_tbl, NULL, ch015_neck_spd_tbl),
    ANM_STD(ch000anm_tbl, NULL, NULL),
    ANM_STD(ch017anm_tbl, ch017morph_tbl, ch017_neck_spd_tbl),
    ANM_STD(ch018anm_tbl, NULL, ch018_neck_spd_tbl),
    ANM_STD(ch019anm_tbl, NULL, ch019_neck_spd_tbl),
    ANM_STD(ch020anm_tbl, ch020morph_tbl, ch020_neck_spd_tbl),
    ANM_STD(ch021anm_tbl, NULL, ch021_neck_spd_tbl),
    ANM_STD(ch022anm_tbl, NULL, ch022_neck_spd_tbl),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(ch024anm_tbl, NULL, ch024_neck_spd_tbl),
    ANM_STD(ch025anm_tbl, NULL, ch025_neck_spd_tbl),
    ANM_STD(ch026anm_tbl, NULL, ch026_neck_spd_tbl),
    ANM_STD(ch027anm_tbl, NULL, ch027_neck_spd_tbl),
    ANM_STD(ch028anm_tbl, NULL, ch028_neck_spd_tbl),
    ANM_STD(ch029anm_tbl, NULL, ch029_neck_spd_tbl),
    ANM_STD(ch030anm_tbl, ch030morph_tbl, ch030_neck_spd_tbl),
    ANM_STD(ch031anm_tbl, NULL, ch031_neck_spd_tbl),
    ANM_STD(ch032anm_tbl, NULL, ch032_neck_spd_tbl),
    ANM_STD(ch033anm_tbl, NULL, ch033_neck_spd_tbl),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(ch035anm_tbl, NULL, ch035_neck_spd_tbl),
    ANM_STD(ch036anm_tbl, NULL, ch036_neck_spd_tbl),
    ANM_STD(ch037anm_tbl, NULL, ch037_neck_spd_tbl),
    ANM_STD(ch038anm_tbl, NULL, ch038_neck_spd_tbl),
    ANM_STD(ch039anm_tbl, NULL, ch039_neck_spd_tbl),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(ch041anm_tbl, ch041morph_tbl, ch041_neck_spd_tbl),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(test_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(ch046_arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(a017_arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(ch024_a003anm_tbl, NULL, ch024_neck_spd_tbl),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_ENTRY(a031_arei_anm_tbl, NULL, 0.196349531f, a031_neck_spd_tbl),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(ch024_a048anm_tbl, NULL, ch024_neck_spd_tbl),
    ANM_STD(a049_arei_anm_tbl, NULL, a049_neck_spd_tbl),
    ANM_STD(ch038_a050anm_tbl, NULL, ch038_neck_spd_tbl),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(ch031_a060anm_tbl, NULL, ch031_neck_spd_tbl),
    ANM_STD(a061_arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(a068_arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(a095_arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(a111_arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(a129_arei_anm_tbl, NULL, NULL),
    ANM_STD(a130_arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(a140_arei_anm_tbl, NULL, NULL),
    ANM_STD(a141_arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(a145_arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_anm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(arei_loopanm_tbl, NULL, NULL),
    ANM_STD(a191_arei_anm_tbl, NULL, NULL),
    ANM_STD(ch031_a195anm_tbl, NULL, ch013_neck_spd_tbl),
    ANM_STD(ch019_a202anm_tbl, NULL, ch019_neck_spd_tbl),
    ANM_STD(ch024_a204anm_tbl, NULL, ch024_neck_spd_tbl)
};

#undef ANM_STD
#undef ANM_ENTRY
